/**
 * Font package: plusFonts
 * Generated by scripts/generate-font-package/generate-font-package.py — edit as needed.
 *
 * Values are PostScript names — works on both iOS and Android.
 */

export type TFontWeightToken = '200' | '300' | '400' | '500' | '600' | '700' | '800';
export type TFontFamilyMap = Record<TFontWeightToken, string>;
export type TFontPackage = Record<string, TFontFamilyMap>;

export const plusFonts: TFontPackage = {
  plusJakartaSans: {
    '200': 'PlusJakartaSans-ExtraLight',
    '300': 'PlusJakartaSans-Light',
    '400': 'PlusJakartaSans-Regular',
    '500': 'PlusJakartaSans-Medium',
    '600': 'PlusJakartaSans-SemiBold',
    '700': 'PlusJakartaSans-Bold',
    '800': 'PlusJakartaSans-ExtraBold',
  },
};
