/**
 * Font package: plusFonts
 * Generated by scripts/generate-font-package/generate-font-package.py — edit as needed.
 *
 * Values are PostScript names — works on both iOS and Android.
 * Italic keys use the weight suffixed with 'i' (e.g. '400i', '700i').
 */

export type TFontWeightToken = '200' | '300' | '400' | '500' | '600' | '700' | '800' | '200i' | '300i' | '400i' | '500i' | '600i' | '700i' | '800i';
export type TFontFamilyMap = Partial<Record<TFontWeightToken, string>>;
export type TFontPackage = Record<string, TFontFamilyMap>;

export const plusFonts: TFontPackage = {
  plusJakartaSans: {
    '200': 'PlusJakartaSans-ExtraLight',
    '300': 'PlusJakartaSans-Light',
    '400': 'PlusJakartaSans-Regular',
    '500': 'PlusJakartaSans-Medium',
    '600': 'PlusJakartaSans-SemiBold',
    '700': 'PlusJakartaSans-Bold',
    '800': 'PlusJakartaSans-ExtraBold',
    '200i': 'PlusJakartaSans-ExtraLightItalic',
    '300i': 'PlusJakartaSans-LightItalic',
    '400i': 'PlusJakartaSans-Italic',
    '500i': 'PlusJakartaSans-MediumItalic',
    '600i': 'PlusJakartaSans-SemiBoldItalic',
    '700i': 'PlusJakartaSans-BoldItalic',
    '800i': 'PlusJakartaSans-ExtraBoldItalic',
  },
};
